// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="compute_check_to_value_compute_check_to_value,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=7581,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=4297,HLS_SYN_LUT=4447,HLS_VERSION=2025_1}" *)

module compute_check_to_value (
        ap_clk,
        ap_rst_n,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 77'd1;
parameter    ap_ST_fsm_state2 = 77'd2;
parameter    ap_ST_fsm_state3 = 77'd4;
parameter    ap_ST_fsm_state4 = 77'd8;
parameter    ap_ST_fsm_state5 = 77'd16;
parameter    ap_ST_fsm_state6 = 77'd32;
parameter    ap_ST_fsm_state7 = 77'd64;
parameter    ap_ST_fsm_state8 = 77'd128;
parameter    ap_ST_fsm_state9 = 77'd256;
parameter    ap_ST_fsm_state10 = 77'd512;
parameter    ap_ST_fsm_state11 = 77'd1024;
parameter    ap_ST_fsm_state12 = 77'd2048;
parameter    ap_ST_fsm_state13 = 77'd4096;
parameter    ap_ST_fsm_state14 = 77'd8192;
parameter    ap_ST_fsm_state15 = 77'd16384;
parameter    ap_ST_fsm_state16 = 77'd32768;
parameter    ap_ST_fsm_state17 = 77'd65536;
parameter    ap_ST_fsm_state18 = 77'd131072;
parameter    ap_ST_fsm_state19 = 77'd262144;
parameter    ap_ST_fsm_state20 = 77'd524288;
parameter    ap_ST_fsm_state21 = 77'd1048576;
parameter    ap_ST_fsm_state22 = 77'd2097152;
parameter    ap_ST_fsm_state23 = 77'd4194304;
parameter    ap_ST_fsm_state24 = 77'd8388608;
parameter    ap_ST_fsm_state25 = 77'd16777216;
parameter    ap_ST_fsm_state26 = 77'd33554432;
parameter    ap_ST_fsm_state27 = 77'd67108864;
parameter    ap_ST_fsm_state28 = 77'd134217728;
parameter    ap_ST_fsm_state29 = 77'd268435456;
parameter    ap_ST_fsm_state30 = 77'd536870912;
parameter    ap_ST_fsm_state31 = 77'd1073741824;
parameter    ap_ST_fsm_state32 = 77'd2147483648;
parameter    ap_ST_fsm_state33 = 77'd4294967296;
parameter    ap_ST_fsm_state34 = 77'd8589934592;
parameter    ap_ST_fsm_state35 = 77'd17179869184;
parameter    ap_ST_fsm_state36 = 77'd34359738368;
parameter    ap_ST_fsm_state37 = 77'd68719476736;
parameter    ap_ST_fsm_state38 = 77'd137438953472;
parameter    ap_ST_fsm_state39 = 77'd274877906944;
parameter    ap_ST_fsm_state40 = 77'd549755813888;
parameter    ap_ST_fsm_state41 = 77'd1099511627776;
parameter    ap_ST_fsm_state42 = 77'd2199023255552;
parameter    ap_ST_fsm_state43 = 77'd4398046511104;
parameter    ap_ST_fsm_state44 = 77'd8796093022208;
parameter    ap_ST_fsm_state45 = 77'd17592186044416;
parameter    ap_ST_fsm_state46 = 77'd35184372088832;
parameter    ap_ST_fsm_state47 = 77'd70368744177664;
parameter    ap_ST_fsm_state48 = 77'd140737488355328;
parameter    ap_ST_fsm_state49 = 77'd281474976710656;
parameter    ap_ST_fsm_state50 = 77'd562949953421312;
parameter    ap_ST_fsm_state51 = 77'd1125899906842624;
parameter    ap_ST_fsm_state52 = 77'd2251799813685248;
parameter    ap_ST_fsm_state53 = 77'd4503599627370496;
parameter    ap_ST_fsm_state54 = 77'd9007199254740992;
parameter    ap_ST_fsm_state55 = 77'd18014398509481984;
parameter    ap_ST_fsm_state56 = 77'd36028797018963968;
parameter    ap_ST_fsm_state57 = 77'd72057594037927936;
parameter    ap_ST_fsm_state58 = 77'd144115188075855872;
parameter    ap_ST_fsm_state59 = 77'd288230376151711744;
parameter    ap_ST_fsm_state60 = 77'd576460752303423488;
parameter    ap_ST_fsm_state61 = 77'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 77'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 77'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 77'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 77'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 77'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 77'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 77'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 77'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 77'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 77'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 77'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 77'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 77'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 77'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 77'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 77'd75557863725914323419136;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
wire    ap_continue;
reg    ap_done_reg;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [76:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] L;
wire   [63:0] syndrome;
wire   [63:0] out_r;
wire   [31:0] size_checks;
wire   [31:0] size_vnode;
reg    gmem0_blk_n_AR;
wire    ap_CS_fsm_state4;
reg    gmem0_blk_n_R;
wire    ap_CS_fsm_state75;
reg   [31:0] size_vnode_read_reg_371;
reg    ap_block_state1;
reg   [63:0] out_r_read_reg_376;
reg   [63:0] syndrome_read_reg_381;
reg   [63:0] L_read_reg_386;
wire   [5:0] select_ln12_fu_217_p3;
reg   [5:0] select_ln12_reg_415;
wire   [4:0] select_ln12_1_fu_235_p3;
reg   [4:0] select_ln12_1_reg_420;
wire   [11:0] empty_31_fu_296_p1;
reg   [11:0] empty_31_reg_428;
wire    ap_CS_fsm_state2;
wire   [63:0] empty_32_fu_300_p2;
reg   [63:0] empty_32_reg_433;
reg   [63:0] gmem0_addr_reg_439;
reg   [31:0] gmem0_addr_read_reg_445;
reg    gmem0_0_AWVALID;
wire    gmem0_0_AWREADY;
reg    gmem0_0_WVALID;
wire    gmem0_0_WREADY;
reg    gmem0_0_ARVALID;
wire    gmem0_0_ARREADY;
wire   [31:0] gmem0_0_ARLEN;
wire    gmem0_0_RVALID;
reg    gmem0_0_RREADY;
wire   [31:0] gmem0_0_RDATA;
wire   [8:0] gmem0_0_RFIFONUM;
wire    gmem0_0_BVALID;
reg    gmem0_0_BREADY;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_ap_start;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_ap_done;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_ap_idle;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_ap_ready;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWVALID;
wire   [63:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWADDR;
wire   [0:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWID;
wire   [31:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWLEN;
wire   [2:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWSIZE;
wire   [1:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWBURST;
wire   [1:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWLOCK;
wire   [3:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWCACHE;
wire   [2:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWPROT;
wire   [3:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWQOS;
wire   [3:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWREGION;
wire   [0:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWUSER;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_WVALID;
wire   [31:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_WDATA;
wire   [3:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_WSTRB;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_WLAST;
wire   [0:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_WID;
wire   [0:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_WUSER;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARVALID;
wire   [63:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARADDR;
wire   [0:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARID;
wire   [31:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARLEN;
wire   [2:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARSIZE;
wire   [1:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARBURST;
wire   [1:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARLOCK;
wire   [3:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARCACHE;
wire   [2:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARPROT;
wire   [3:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARQOS;
wire   [3:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARREGION;
wire   [0:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARUSER;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_RREADY;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_BREADY;
wire   [31:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_min2_3_out;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_min2_3_out_ap_vld;
wire   [31:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_min1_3_out;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_min1_3_out_ap_vld;
wire   [31:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_minpos_2_out;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_minpos_2_out_ap_vld;
wire   [31:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_row_sign_1_out;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_row_sign_1_out_ap_vld;
wire   [31:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_grp_fu_462_p_din0;
wire   [31:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_grp_fu_462_p_din1;
wire   [4:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_grp_fu_462_p_opcode;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_grp_fu_462_p_ce;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_ap_start;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_ap_done;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_ap_idle;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_ap_ready;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWVALID;
wire   [63:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWADDR;
wire   [0:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWID;
wire   [31:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWLEN;
wire   [2:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWSIZE;
wire   [1:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWBURST;
wire   [1:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWLOCK;
wire   [3:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWCACHE;
wire   [2:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWPROT;
wire   [3:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWQOS;
wire   [3:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWREGION;
wire   [0:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWUSER;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_WVALID;
wire   [31:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_WDATA;
wire   [3:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_WSTRB;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_WLAST;
wire   [0:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_WID;
wire   [0:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_WUSER;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARVALID;
wire   [63:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARADDR;
wire   [0:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARID;
wire   [31:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARLEN;
wire   [2:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARSIZE;
wire   [1:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARBURST;
wire   [1:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARLOCK;
wire   [3:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARCACHE;
wire   [2:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARPROT;
wire   [3:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARQOS;
wire   [3:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARREGION;
wire   [0:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARUSER;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_RREADY;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_BREADY;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWVALID;
wire   [63:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWADDR;
wire   [0:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWID;
wire   [31:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWLEN;
wire   [2:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWSIZE;
wire   [1:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWBURST;
wire   [1:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWLOCK;
wire   [3:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWCACHE;
wire   [2:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWPROT;
wire   [3:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWQOS;
wire   [3:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWREGION;
wire   [0:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWUSER;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_WVALID;
wire   [31:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_WDATA;
wire   [3:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_WSTRB;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_WLAST;
wire   [0:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_WID;
wire   [0:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_WUSER;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARVALID;
wire   [63:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARADDR;
wire   [0:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARID;
wire   [31:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARLEN;
wire   [2:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARSIZE;
wire   [1:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARBURST;
wire   [1:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARLOCK;
wire   [3:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARCACHE;
wire   [2:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARPROT;
wire   [3:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARQOS;
wire   [3:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARREGION;
wire   [0:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARUSER;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_RREADY;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_BREADY;
wire   [31:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_grp_fu_462_p_din0;
wire   [31:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_grp_fu_462_p_din1;
wire   [4:0] grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_grp_fu_462_p_opcode;
wire    grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_grp_fu_462_p_ce;
wire    gmem1_0_AWREADY;
wire    gmem1_0_WREADY;
reg    gmem1_0_ARVALID;
wire    gmem1_0_ARREADY;
reg   [63:0] gmem1_0_ARADDR;
reg   [31:0] gmem1_0_ARLEN;
wire    gmem1_0_RVALID;
reg    gmem1_0_RREADY;
wire   [31:0] gmem1_0_RDATA;
wire   [8:0] gmem1_0_RFIFONUM;
wire    gmem1_0_BVALID;
reg    grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_ap_start_reg;
wire   [0:0] icmp_ln12_fu_251_p2;
wire    ap_CS_fsm_state3;
reg   [31:0] min2_3_loc_fu_132;
reg   [31:0] min1_3_loc_fu_128;
reg   [31:0] minpos_2_loc_fu_124;
reg    grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_ap_start_reg;
wire    ap_CS_fsm_state76;
wire    ap_CS_fsm_state77;
wire  signed [63:0] p_cast_cast_fu_333_p1;
reg   [4:0] i_fu_116;
wire   [4:0] add_ln12_fu_256_p2;
wire   [0:0] empty_27_fu_211_p2;
wire   [5:0] empty_fu_207_p1;
wire   [0:0] empty_29_fu_229_p2;
wire   [4:0] empty_28_fu_225_p1;
wire   [11:0] tmp_3_fu_262_p3;
wire   [9:0] tmp_4_fu_274_p3;
wire   [12:0] p_shl_fu_270_p1;
wire   [12:0] p_shl16_fu_282_p1;
wire   [12:0] empty_30_fu_286_p2;
wire   [63:0] p_cast5_fu_292_p1;
wire   [6:0] tmp_fu_306_p3;
wire   [63:0] p_cast7_fu_314_p1;
wire   [63:0] empty_33_fu_318_p2;
wire   [61:0] p_cast_fu_323_p4;
wire   [0:0] grp_fu_462_p2;
reg   [31:0] grp_fu_462_p0;
reg   [31:0] grp_fu_462_p1;
reg    grp_fu_462_ce;
reg   [4:0] grp_fu_462_opcode;
reg   [76:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
wire    ap_ST_fsm_state74_blk;
reg    ap_ST_fsm_state75_blk;
wire    ap_ST_fsm_state76_blk;
reg    ap_ST_fsm_state77_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 77'd1;
#0 grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_ap_start_reg = 1'b0;
#0 grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_ap_start_reg = 1'b0;
#0 i_fu_116 = 5'd0;
end

compute_check_to_value_compute_check_to_value_Pipeline_VITIS_LOOP_21_2 grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_ap_start),
    .ap_done(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_ap_done),
    .ap_idle(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_ap_idle),
    .ap_ready(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_ap_ready),
    .m_axi_gmem1_0_AWVALID(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWVALID),
    .m_axi_gmem1_0_AWREADY(1'b0),
    .m_axi_gmem1_0_AWADDR(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWADDR),
    .m_axi_gmem1_0_AWID(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWID),
    .m_axi_gmem1_0_AWLEN(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWLEN),
    .m_axi_gmem1_0_AWSIZE(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWSIZE),
    .m_axi_gmem1_0_AWBURST(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWBURST),
    .m_axi_gmem1_0_AWLOCK(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWLOCK),
    .m_axi_gmem1_0_AWCACHE(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWCACHE),
    .m_axi_gmem1_0_AWPROT(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWPROT),
    .m_axi_gmem1_0_AWQOS(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWQOS),
    .m_axi_gmem1_0_AWREGION(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWREGION),
    .m_axi_gmem1_0_AWUSER(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_AWUSER),
    .m_axi_gmem1_0_WVALID(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_WVALID),
    .m_axi_gmem1_0_WREADY(1'b0),
    .m_axi_gmem1_0_WDATA(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_WDATA),
    .m_axi_gmem1_0_WSTRB(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_WSTRB),
    .m_axi_gmem1_0_WLAST(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_WLAST),
    .m_axi_gmem1_0_WID(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_WID),
    .m_axi_gmem1_0_WUSER(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_WUSER),
    .m_axi_gmem1_0_ARVALID(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARVALID),
    .m_axi_gmem1_0_ARREADY(gmem1_0_ARREADY),
    .m_axi_gmem1_0_ARADDR(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARADDR),
    .m_axi_gmem1_0_ARID(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARID),
    .m_axi_gmem1_0_ARLEN(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARLEN),
    .m_axi_gmem1_0_ARSIZE(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARSIZE),
    .m_axi_gmem1_0_ARBURST(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARBURST),
    .m_axi_gmem1_0_ARLOCK(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARLOCK),
    .m_axi_gmem1_0_ARCACHE(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARCACHE),
    .m_axi_gmem1_0_ARPROT(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARPROT),
    .m_axi_gmem1_0_ARQOS(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARQOS),
    .m_axi_gmem1_0_ARREGION(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARREGION),
    .m_axi_gmem1_0_ARUSER(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARUSER),
    .m_axi_gmem1_0_RVALID(gmem1_0_RVALID),
    .m_axi_gmem1_0_RREADY(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_RREADY),
    .m_axi_gmem1_0_RDATA(gmem1_0_RDATA),
    .m_axi_gmem1_0_RLAST(1'b0),
    .m_axi_gmem1_0_RID(1'd0),
    .m_axi_gmem1_0_RFIFONUM(gmem1_0_RFIFONUM),
    .m_axi_gmem1_0_RUSER(1'd0),
    .m_axi_gmem1_0_RRESP(2'd0),
    .m_axi_gmem1_0_BVALID(1'b0),
    .m_axi_gmem1_0_BREADY(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_BREADY),
    .m_axi_gmem1_0_BRESP(2'd0),
    .m_axi_gmem1_0_BID(1'd0),
    .m_axi_gmem1_0_BUSER(1'd0),
    .empty(empty_32_reg_433),
    .size_vnode(size_vnode_read_reg_371),
    .min2_3_out(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_min2_3_out),
    .min2_3_out_ap_vld(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_min2_3_out_ap_vld),
    .min1_3_out(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_min1_3_out),
    .min1_3_out_ap_vld(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_min1_3_out_ap_vld),
    .minpos_2_out(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_minpos_2_out),
    .minpos_2_out_ap_vld(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_minpos_2_out_ap_vld),
    .row_sign_1_out(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_row_sign_1_out),
    .row_sign_1_out_ap_vld(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_row_sign_1_out_ap_vld),
    .grp_fu_462_p_din0(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_grp_fu_462_p_din0),
    .grp_fu_462_p_din1(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_grp_fu_462_p_din1),
    .grp_fu_462_p_opcode(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_grp_fu_462_p_opcode),
    .grp_fu_462_p_dout0(grp_fu_462_p2),
    .grp_fu_462_p_ce(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_grp_fu_462_p_ce)
);

compute_check_to_value_compute_check_to_value_Pipeline_VITIS_LOOP_36_3 grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_ap_start),
    .ap_done(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_ap_done),
    .ap_idle(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_ap_idle),
    .ap_ready(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_ap_ready),
    .m_axi_gmem1_0_AWVALID(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWVALID),
    .m_axi_gmem1_0_AWREADY(1'b0),
    .m_axi_gmem1_0_AWADDR(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWADDR),
    .m_axi_gmem1_0_AWID(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWID),
    .m_axi_gmem1_0_AWLEN(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWLEN),
    .m_axi_gmem1_0_AWSIZE(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWSIZE),
    .m_axi_gmem1_0_AWBURST(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWBURST),
    .m_axi_gmem1_0_AWLOCK(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWLOCK),
    .m_axi_gmem1_0_AWCACHE(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWCACHE),
    .m_axi_gmem1_0_AWPROT(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWPROT),
    .m_axi_gmem1_0_AWQOS(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWQOS),
    .m_axi_gmem1_0_AWREGION(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWREGION),
    .m_axi_gmem1_0_AWUSER(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_AWUSER),
    .m_axi_gmem1_0_WVALID(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_WVALID),
    .m_axi_gmem1_0_WREADY(1'b0),
    .m_axi_gmem1_0_WDATA(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_WDATA),
    .m_axi_gmem1_0_WSTRB(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_WSTRB),
    .m_axi_gmem1_0_WLAST(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_WLAST),
    .m_axi_gmem1_0_WID(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_WID),
    .m_axi_gmem1_0_WUSER(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_WUSER),
    .m_axi_gmem1_0_ARVALID(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARVALID),
    .m_axi_gmem1_0_ARREADY(gmem1_0_ARREADY),
    .m_axi_gmem1_0_ARADDR(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARADDR),
    .m_axi_gmem1_0_ARID(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARID),
    .m_axi_gmem1_0_ARLEN(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARLEN),
    .m_axi_gmem1_0_ARSIZE(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARSIZE),
    .m_axi_gmem1_0_ARBURST(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARBURST),
    .m_axi_gmem1_0_ARLOCK(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARLOCK),
    .m_axi_gmem1_0_ARCACHE(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARCACHE),
    .m_axi_gmem1_0_ARPROT(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARPROT),
    .m_axi_gmem1_0_ARQOS(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARQOS),
    .m_axi_gmem1_0_ARREGION(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARREGION),
    .m_axi_gmem1_0_ARUSER(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARUSER),
    .m_axi_gmem1_0_RVALID(gmem1_0_RVALID),
    .m_axi_gmem1_0_RREADY(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_RREADY),
    .m_axi_gmem1_0_RDATA(gmem1_0_RDATA),
    .m_axi_gmem1_0_RLAST(1'b0),
    .m_axi_gmem1_0_RID(1'd0),
    .m_axi_gmem1_0_RFIFONUM(gmem1_0_RFIFONUM),
    .m_axi_gmem1_0_RUSER(1'd0),
    .m_axi_gmem1_0_RRESP(2'd0),
    .m_axi_gmem1_0_BVALID(1'b0),
    .m_axi_gmem1_0_BREADY(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_BREADY),
    .m_axi_gmem1_0_BRESP(2'd0),
    .m_axi_gmem1_0_BID(1'd0),
    .m_axi_gmem1_0_BUSER(1'd0),
    .m_axi_gmem0_0_AWVALID(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(gmem0_0_AWREADY),
    .m_axi_gmem0_0_AWADDR(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(gmem0_0_WREADY),
    .m_axi_gmem0_0_WDATA(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(1'b0),
    .m_axi_gmem0_0_ARADDR(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(1'b0),
    .m_axi_gmem0_0_RREADY(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(32'd0),
    .m_axi_gmem0_0_RLAST(1'b0),
    .m_axi_gmem0_0_RID(1'd0),
    .m_axi_gmem0_0_RFIFONUM(9'd0),
    .m_axi_gmem0_0_RUSER(1'd0),
    .m_axi_gmem0_0_RRESP(2'd0),
    .m_axi_gmem0_0_BVALID(gmem0_0_BVALID),
    .m_axi_gmem0_0_BREADY(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(2'd0),
    .m_axi_gmem0_0_BID(1'd0),
    .m_axi_gmem0_0_BUSER(1'd0),
    .select_ln12(select_ln12_reg_415),
    .empty(empty_32_reg_433),
    .row_sign_1_reload(grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_row_sign_1_out),
    .gmem0_load(gmem0_addr_read_reg_445),
    .minpos_2_reload(minpos_2_loc_fu_124),
    .min1_3_reload(min1_3_loc_fu_128),
    .min2_3_reload(min2_3_loc_fu_132),
    .out_r(out_r_read_reg_376),
    .p_cast5(empty_31_reg_428),
    .grp_fu_462_p_din0(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_grp_fu_462_p_din0),
    .grp_fu_462_p_din1(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_grp_fu_462_p_din1),
    .grp_fu_462_p_opcode(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_grp_fu_462_p_opcode),
    .grp_fu_462_p_dout0(grp_fu_462_p2),
    .grp_fu_462_p_ce(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_grp_fu_462_p_ce)
);

compute_check_to_value_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .L(L),
    .syndrome(syndrome),
    .out_r(out_r),
    .size_checks(size_checks),
    .size_vnode(size_vnode),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

compute_check_to_value_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 70 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem0_0_ARVALID),
    .I_CH0_ARREADY(gmem0_0_ARREADY),
    .I_CH0_ARADDR(gmem0_addr_reg_439),
    .I_CH0_ARLEN(gmem0_0_ARLEN),
    .I_CH0_RVALID(gmem0_0_RVALID),
    .I_CH0_RREADY(gmem0_0_RREADY),
    .I_CH0_RDATA(gmem0_0_RDATA),
    .I_CH0_RFIFONUM(gmem0_0_RFIFONUM),
    .I_CH0_AWVALID(gmem0_0_AWVALID),
    .I_CH0_AWREADY(gmem0_0_AWREADY),
    .I_CH0_AWADDR(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWADDR),
    .I_CH0_AWLEN(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWLEN),
    .I_CH0_WVALID(gmem0_0_WVALID),
    .I_CH0_WREADY(gmem0_0_WREADY),
    .I_CH0_WDATA(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_WDATA),
    .I_CH0_WSTRB(grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_WSTRB),
    .I_CH0_BVALID(gmem0_0_BVALID),
    .I_CH0_BREADY(gmem0_0_BREADY)
);

compute_check_to_value_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 70 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem1_0_ARVALID),
    .I_CH0_ARREADY(gmem1_0_ARREADY),
    .I_CH0_ARADDR(gmem1_0_ARADDR),
    .I_CH0_ARLEN(gmem1_0_ARLEN),
    .I_CH0_RVALID(gmem1_0_RVALID),
    .I_CH0_RREADY(gmem1_0_RREADY),
    .I_CH0_RDATA(gmem1_0_RDATA),
    .I_CH0_RFIFONUM(gmem1_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem1_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem1_0_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(gmem1_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

compute_check_to_value_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U26(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_462_p0),
    .din1(grp_fu_462_p1),
    .ce(grp_fu_462_ce),
    .opcode(grp_fu_462_opcode),
    .dout(grp_fu_462_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln12_fu_251_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln12_fu_251_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_ap_start_reg <= 1'b1;
        end else if ((grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_ap_ready == 1'b1)) begin
            grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state76)) begin
            grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_ap_start_reg <= 1'b1;
        end else if ((grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_ap_ready == 1'b1)) begin
            grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_116 <= 5'd0;
    end else if (((icmp_ln12_fu_251_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_116 <= add_ln12_fu_256_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        L_read_reg_386 <= L;
        out_r_read_reg_376 <= out_r;
        select_ln12_1_reg_420 <= select_ln12_1_fu_235_p3;
        select_ln12_reg_415 <= select_ln12_fu_217_p3;
        size_vnode_read_reg_371 <= size_vnode;
        syndrome_read_reg_381 <= syndrome;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        empty_31_reg_428[11 : 5] <= empty_31_fu_296_p1[11 : 5];
        empty_32_reg_433 <= empty_32_fu_300_p2;
        gmem0_addr_reg_439 <= p_cast_cast_fu_333_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((gmem0_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state75))) begin
        gmem0_addr_read_reg_445 <= gmem0_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_min1_3_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        min1_3_loc_fu_128 <= grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_min1_3_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_min2_3_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        min2_3_loc_fu_132 <= grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_min2_3_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_minpos_2_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        minpos_2_loc_fu_124 <= grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_minpos_2_out;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

always @ (*) begin
    if ((grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

always @ (*) begin
    if ((gmem0_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

assign ap_ST_fsm_state74_blk = 1'b0;

always @ (*) begin
    if ((gmem0_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state75_blk = 1'b1;
    end else begin
        ap_ST_fsm_state75_blk = 1'b0;
    end
end

assign ap_ST_fsm_state76_blk = 1'b0;

always @ (*) begin
    if ((grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_ap_done == 1'b0)) begin
        ap_ST_fsm_state77_blk = 1'b1;
    end else begin
        ap_ST_fsm_state77_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln12_fu_251_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln12_fu_251_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((gmem0_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        gmem0_0_ARVALID = 1'b1;
    end else begin
        gmem0_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state76))) begin
        gmem0_0_AWVALID = grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_AWVALID;
    end else begin
        gmem0_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state76))) begin
        gmem0_0_BREADY = grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_BREADY;
    end else begin
        gmem0_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((gmem0_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state75))) begin
        gmem0_0_RREADY = 1'b1;
    end else begin
        gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state76))) begin
        gmem0_0_WVALID = grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem0_0_WVALID;
    end else begin
        gmem0_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        gmem0_blk_n_AR = m_axi_gmem0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state75)) begin
        gmem0_blk_n_R = m_axi_gmem0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state76))) begin
        gmem1_0_ARADDR = grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem1_0_ARADDR = grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARADDR;
    end else begin
        gmem1_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state76))) begin
        gmem1_0_ARLEN = grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem1_0_ARLEN = grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARLEN;
    end else begin
        gmem1_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state76))) begin
        gmem1_0_ARVALID = grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem1_0_ARVALID = grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_ARVALID;
    end else begin
        gmem1_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state76))) begin
        gmem1_0_RREADY = grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_m_axi_gmem1_0_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem1_0_RREADY = grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_m_axi_gmem1_0_RREADY;
    end else begin
        gmem1_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state77)) begin
        grp_fu_462_ce = grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_grp_fu_462_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_462_ce = grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_grp_fu_462_p_ce;
    end else begin
        grp_fu_462_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state77)) begin
        grp_fu_462_opcode = grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_grp_fu_462_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_462_opcode = grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_grp_fu_462_p_opcode;
    end else begin
        grp_fu_462_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state77)) begin
        grp_fu_462_p0 = grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_grp_fu_462_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_462_p0 = grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_grp_fu_462_p_din0;
    end else begin
        grp_fu_462_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state77)) begin
        grp_fu_462_p1 = grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_grp_fu_462_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_462_p1 = grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_grp_fu_462_p_din1;
    end else begin
        grp_fu_462_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln12_fu_251_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((gmem0_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            if (((gmem0_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state75))) begin
                ap_NS_fsm = ap_ST_fsm_state76;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state75;
            end
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            if (((grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state77))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state77;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln12_fu_256_p2 = (i_fu_116 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state75 = ap_CS_fsm[32'd74];

assign ap_CS_fsm_state76 = ap_CS_fsm[32'd75];

assign ap_CS_fsm_state77 = ap_CS_fsm[32'd76];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign empty_27_fu_211_p2 = ((size_vnode < 32'd40) ? 1'b1 : 1'b0);

assign empty_28_fu_225_p1 = size_checks[4:0];

assign empty_29_fu_229_p2 = ((size_checks < 32'd20) ? 1'b1 : 1'b0);

assign empty_30_fu_286_p2 = (p_shl_fu_270_p1 + p_shl16_fu_282_p1);

assign empty_31_fu_296_p1 = empty_30_fu_286_p2[11:0];

assign empty_32_fu_300_p2 = (p_cast5_fu_292_p1 + L_read_reg_386);

assign empty_33_fu_318_p2 = (p_cast7_fu_314_p1 + syndrome_read_reg_381);

assign empty_fu_207_p1 = size_vnode[5:0];

assign gmem0_0_ARLEN = 64'd1;

assign grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_ap_start = grp_compute_check_to_value_Pipeline_VITIS_LOOP_21_2_fu_178_ap_start_reg;

assign grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_ap_start = grp_compute_check_to_value_Pipeline_VITIS_LOOP_36_3_fu_190_ap_start_reg;

assign icmp_ln12_fu_251_p2 = ((i_fu_116 == select_ln12_1_reg_420) ? 1'b1 : 1'b0);

assign p_cast5_fu_292_p1 = empty_30_fu_286_p2;

assign p_cast7_fu_314_p1 = tmp_fu_306_p3;

assign p_cast_cast_fu_333_p1 = $signed(p_cast_fu_323_p4);

assign p_cast_fu_323_p4 = {{empty_33_fu_318_p2[63:2]}};

assign p_shl16_fu_282_p1 = tmp_4_fu_274_p3;

assign p_shl_fu_270_p1 = tmp_3_fu_262_p3;

assign select_ln12_1_fu_235_p3 = ((empty_29_fu_229_p2[0:0] == 1'b1) ? empty_28_fu_225_p1 : 5'd20);

assign select_ln12_fu_217_p3 = ((empty_27_fu_211_p2[0:0] == 1'b1) ? empty_fu_207_p1 : 6'd40);

assign tmp_3_fu_262_p3 = {{i_fu_116}, {7'd0}};

assign tmp_4_fu_274_p3 = {{i_fu_116}, {5'd0}};

assign tmp_fu_306_p3 = {{i_fu_116}, {2'd0}};

always @ (posedge ap_clk) begin
    empty_31_reg_428[4:0] <= 5'b00000;
end

endmodule //compute_check_to_value
