

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "23", "25", "27", "88", "91", "92", "93", "94"],
		"CDFG" : "compute_row_operations",
		"Protocol" : "ap_ctrl_chain",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "214", "EstimateLatencyMax" : "245",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "IO",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem0_blk_n_B", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "21", "SubInstance" : "grp_compute_row_operations_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_17_2_fu_261", "Port" : "gmem0", "Inst_start_state" : "73", "Inst_end_state" : "74"},
					{"ID" : "88", "SubInstance" : "grp_compute_row_operations_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_89_10_fu_336", "Port" : "gmem0", "Inst_start_state" : "77", "Inst_end_state" : "78"}]},
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_compute_row_operations_Pipeline_VITIS_LOOP_23_3_VITIS_LOOP_25_4_fu_278", "Port" : "gmem1", "Inst_start_state" : "73", "Inst_end_state" : "74"}]},
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem2_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "25", "SubInstance" : "grp_compute_row_operations_Pipeline_VITIS_LOOP_31_5_fu_295", "Port" : "gmem2", "Inst_start_state" : "73", "Inst_end_state" : "74"}]},
			{"Name" : "L", "Type" : "None", "Direction" : "I"},
			{"Name" : "non_zero", "Type" : "None", "Direction" : "I"},
			{"Name" : "syndrome", "Type" : "None", "Direction" : "I"},
			{"Name" : "size_checks", "Type" : "None", "Direction" : "I"},
			{"Name" : "size_vnode", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.L_cache_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.L_cache_1_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.L_cache_2_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.L_cache_3_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.L_cache_4_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.L_cache_5_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.L_cache_6_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.L_cache_7_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.L_cache_8_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.L_cache_9_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.non_zero_cache_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.non_zero_cache_1_U", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.non_zero_cache_2_U", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.non_zero_cache_3_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.non_zero_cache_4_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.non_zero_cache_5_U", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.non_zero_cache_6_U", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.non_zero_cache_7_U", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.non_zero_cache_8_U", "Parent" : "0"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.non_zero_cache_9_U", "Parent" : "0"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_17_2_fu_261", "Parent" : "0", "Child" : ["22"],
		"CDFG" : "compute_row_operations_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_17_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "33", "EstimateLatencyMax" : "33",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln15", "Type" : "None", "Direction" : "I"},
			{"Name" : "L_cache", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "L_cache_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "L_cache_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "L_cache_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "L_cache_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "L_cache_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "L_cache_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "L_cache_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "L_cache_8", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "L_cache_9", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_15_1_VITIS_LOOP_17_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_15_1_VITIS_LOOP_17_2_fu_261.flow_control_loop_pipe_sequential_init_U", "Parent" : "21"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_23_3_VITIS_LOOP_25_4_fu_278", "Parent" : "0", "Child" : ["24"],
		"CDFG" : "compute_row_operations_Pipeline_VITIS_LOOP_23_3_VITIS_LOOP_25_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "33", "EstimateLatencyMax" : "33",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln23", "Type" : "None", "Direction" : "I"},
			{"Name" : "non_zero_cache", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "non_zero_cache_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "non_zero_cache_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "non_zero_cache_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "non_zero_cache_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "non_zero_cache_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "non_zero_cache_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "non_zero_cache_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "non_zero_cache_8", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "non_zero_cache_9", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_23_3_VITIS_LOOP_25_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_23_3_VITIS_LOOP_25_4_fu_278.flow_control_loop_pipe_sequential_init_U", "Parent" : "23"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_31_5_fu_295", "Parent" : "0", "Child" : ["26"],
		"CDFG" : "compute_row_operations_Pipeline_VITIS_LOOP_31_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "5", "EstimateLatencyMax" : "5",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem2_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "syndrome", "Type" : "None", "Direction" : "I"},
			{"Name" : "syndrome_cache_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "syndrome_cache_1_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "syndrome_cache_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_31_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_31_5_fu_295.flow_control_loop_pipe_sequential_init_U", "Parent" : "25"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305", "Parent" : "0", "Child" : ["28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87"],
		"CDFG" : "compute_row_operations_Pipeline_VITIS_LOOP_37_6",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "33",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "size_vnode", "Type" : "None", "Direction" : "I"},
			{"Name" : "syndrome_cache_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "syndrome_cache_1_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "syndrome_cache_2_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "L_cache_1", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "L_cache_2", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "L_cache_3", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "L_cache_4", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "L_cache_5", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "L_cache_6", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "L_cache_7", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "L_cache_8", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "L_cache_9", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "L_cache", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "size_checks", "Type" : "None", "Direction" : "I"},
			{"Name" : "non_zero_cache", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "non_zero_cache_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "non_zero_cache_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "non_zero_cache_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "non_zero_cache_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "non_zero_cache_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "non_zero_cache_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "non_zero_cache_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "non_zero_cache_8", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "non_zero_cache_9", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_37_6", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter13", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter13", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fsub_32ns_32ns_32_4_full_dsp_1_U30", "Parent" : "27"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fsub_32ns_32ns_32_4_full_dsp_1_U31", "Parent" : "27"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fsub_32ns_32ns_32_4_full_dsp_1_U32", "Parent" : "27"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fsub_32ns_32ns_32_4_full_dsp_1_U33", "Parent" : "27"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fsub_32ns_32ns_32_4_full_dsp_1_U34", "Parent" : "27"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fsub_32ns_32ns_32_4_full_dsp_1_U35", "Parent" : "27"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fmul_32ns_32ns_32_3_max_dsp_1_U36", "Parent" : "27"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fmul_32ns_32ns_32_3_max_dsp_1_U37", "Parent" : "27"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fmul_32ns_32ns_32_3_max_dsp_1_U38", "Parent" : "27"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fmul_32ns_32ns_32_3_max_dsp_1_U39", "Parent" : "27"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fmul_32ns_32ns_32_3_max_dsp_1_U40", "Parent" : "27"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fmul_32ns_32ns_32_3_max_dsp_1_U41", "Parent" : "27"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fmul_32ns_32ns_32_3_max_dsp_1_U42", "Parent" : "27"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fmul_32ns_32ns_32_3_max_dsp_1_U43", "Parent" : "27"},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fmul_32ns_32ns_32_3_max_dsp_1_U44", "Parent" : "27"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fmul_32ns_32ns_32_3_max_dsp_1_U45", "Parent" : "27"},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fmul_32ns_32ns_32_3_max_dsp_1_U46", "Parent" : "27"},
	{"ID" : "45", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.uitofp_32ns_32_4_no_dsp_1_U47", "Parent" : "27"},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.uitofp_32ns_32_4_no_dsp_1_U48", "Parent" : "27"},
	{"ID" : "47", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.uitofp_32ns_32_4_no_dsp_1_U49", "Parent" : "27"},
	{"ID" : "48", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.uitofp_32ns_32_4_no_dsp_1_U50", "Parent" : "27"},
	{"ID" : "49", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.uitofp_32ns_32_4_no_dsp_1_U51", "Parent" : "27"},
	{"ID" : "50", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.uitofp_32ns_32_4_no_dsp_1_U52", "Parent" : "27"},
	{"ID" : "51", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fpext_32ns_64_2_no_dsp_1_U53", "Parent" : "27"},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fpext_32ns_64_2_no_dsp_1_U54", "Parent" : "27"},
	{"ID" : "53", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fpext_32ns_64_2_no_dsp_1_U55", "Parent" : "27"},
	{"ID" : "54", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fpext_32ns_64_2_no_dsp_1_U56", "Parent" : "27"},
	{"ID" : "55", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fpext_32ns_64_2_no_dsp_1_U57", "Parent" : "27"},
	{"ID" : "56", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fcmp_32ns_32ns_1_2_no_dsp_1_U58", "Parent" : "27"},
	{"ID" : "57", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fcmp_32ns_32ns_1_2_no_dsp_1_U59", "Parent" : "27"},
	{"ID" : "58", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fcmp_32ns_32ns_1_2_no_dsp_1_U60", "Parent" : "27"},
	{"ID" : "59", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fcmp_32ns_32ns_1_2_no_dsp_1_U61", "Parent" : "27"},
	{"ID" : "60", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fcmp_32ns_32ns_1_2_no_dsp_1_U62", "Parent" : "27"},
	{"ID" : "61", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fcmp_32ns_32ns_1_2_no_dsp_1_U63", "Parent" : "27"},
	{"ID" : "62", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fcmp_32ns_32ns_1_2_no_dsp_1_U64", "Parent" : "27"},
	{"ID" : "63", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fcmp_32ns_32ns_1_2_no_dsp_1_U65", "Parent" : "27"},
	{"ID" : "64", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fcmp_32ns_32ns_1_2_no_dsp_1_U66", "Parent" : "27"},
	{"ID" : "65", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.fcmp_32ns_32ns_1_2_no_dsp_1_U67", "Parent" : "27"},
	{"ID" : "66", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.sparsemux_7_2_1_1_1_U68", "Parent" : "27"},
	{"ID" : "67", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.sparsemux_7_2_1_1_1_U69", "Parent" : "27"},
	{"ID" : "68", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.sparsemux_7_2_1_1_1_U70", "Parent" : "27"},
	{"ID" : "69", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.sparsemux_7_2_1_1_1_U71", "Parent" : "27"},
	{"ID" : "70", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.sparsemux_7_2_32_1_1_U72", "Parent" : "27"},
	{"ID" : "71", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.sparsemux_7_2_32_1_1_U73", "Parent" : "27"},
	{"ID" : "72", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.sparsemux_21_9_1_1_1_U74", "Parent" : "27"},
	{"ID" : "73", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.sparsemux_7_2_1_1_1_U75", "Parent" : "27"},
	{"ID" : "74", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.sparsemux_7_2_1_1_1_U76", "Parent" : "27"},
	{"ID" : "75", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.sparsemux_7_2_32_1_1_U77", "Parent" : "27"},
	{"ID" : "76", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.sparsemux_7_2_32_1_1_U78", "Parent" : "27"},
	{"ID" : "77", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.sparsemux_7_2_32_1_1_U79", "Parent" : "27"},
	{"ID" : "78", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.sparsemux_7_2_32_1_1_U80", "Parent" : "27"},
	{"ID" : "79", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.sparsemux_7_2_32_1_1_U81", "Parent" : "27"},
	{"ID" : "80", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.sparsemux_7_2_32_1_1_U82", "Parent" : "27"},
	{"ID" : "81", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.sparsemux_7_2_1_1_1_U83", "Parent" : "27"},
	{"ID" : "82", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.sparsemux_7_2_32_1_1_U84", "Parent" : "27"},
	{"ID" : "83", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.sparsemux_21_9_1_1_1_U85", "Parent" : "27"},
	{"ID" : "84", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.sparsemux_21_9_32_1_1_U86", "Parent" : "27"},
	{"ID" : "85", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.sparsemux_21_9_32_1_1_U87", "Parent" : "27"},
	{"ID" : "86", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.sparsemux_21_9_5_1_1_U88", "Parent" : "27"},
	{"ID" : "87", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_37_6_fu_305.flow_control_loop_pipe_sequential_init_U", "Parent" : "27"},
	{"ID" : "88", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_89_10_fu_336", "Parent" : "0", "Child" : ["89", "90"],
		"CDFG" : "compute_row_operations_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_89_10",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "34", "EstimateLatencyMax" : "34",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_W", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln15", "Type" : "None", "Direction" : "I"},
			{"Name" : "L_cache", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "L_cache_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "L_cache_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "L_cache_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "L_cache_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "L_cache_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "L_cache_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "L_cache_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "L_cache_8", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "L_cache_9", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_87_9_VITIS_LOOP_89_10", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "89", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_89_10_fu_336.sparsemux_21_4_32_1_1_U124", "Parent" : "88"},
	{"ID" : "90", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_compute_row_operations_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_89_10_fu_336.flow_control_loop_pipe_sequential_init_U", "Parent" : "88"},
	{"ID" : "91", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "92", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_m_axi_U", "Parent" : "0"},
	{"ID" : "93", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_m_axi_U", "Parent" : "0"},
	{"ID" : "94", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem2_m_axi_U", "Parent" : "0"}]}
